### PR TITLE
Replace to new emerald ore texture from JSC

### PR DESCRIPTION
**Pull request by Ghostlyr**
Old texture has not frames and causes errors...

### CODE REVIEW

**Comment by Oddface** [comment]
Thanks for spotting this bug. I didn't realize the emerald ore had been changed. I think I'd rather change it back to how it was before, though. Anyone else have an opinion on this?

**Comment by Ghostlyr** [comment]
I liked a new texture. I think old it too rough :)

**Comment by Greenhawk837** [comment]
I'm not a fan of that emerald ore either. I say just leave it as it is.

**Comment by Oddface** [comment]
Alright, I'm gonna say this is settled. I've reverted the emerald item and removed the mcmeta that was screwing up the ore texture.

**Pull request closed without merging**
