### PR TITLE
Legacy Conversion

### PR DESCRIPTION
**Pull request by goldbattle**

### CODE REVIEW

**Comment by lesdmark** [comment]
Is this for a parallel legacy version that will exist in addition to the one we have now?

**Comment by Greenhawk837** [comment]
That's what I am assuming will happen, have the legacy ores as another overwrites pack

**Comment by Oddface** [comment]
That's what I thought I was doing, but goldbattle seems to be talking about a change to the whole pack. I always prefered the Legacy look, so I wouldn't mind. I don't know how everyone else would feel about it, though.

**Comment by Greenhawk837** [comment]
I don't want to see the Legacy ores replace the current smooth look, and I don't think too many other people would either. 

Back in 2012 we had a Legacy version of the pack, just the ores, dirt and stone was changed. It was barely downloaded compared to the main pack. After a while it was just put on hold. because of the amount of people using it and that nobody that worked on the pack used it themselves. 

But I would still love to see it as an option for people again, by using an overwrite pack.

**Comment by Oddface** [comment]
As someone who played vanilla for years with the regular John Smith pack before moving onto modded Minecraft, JSTR just kinda looks wrong to me. And this change could very well have the same effect on someone who has been using JSTR for years. An interesting experiment could be to make JSTR the overwrite pack and look at the response. My guess is that the people who feel strongly enough about one style or another to download an overwrite pack is always going to be a minor fraction of the user base. If I'm wrong about that, changing it back wouldn't be a big deal. I think now would be a good time to experiment with big changes like this.

**Comment by goldbattle** [comment]
Just let me know what you end up doing so I can build the right packs. I
was going to release a beta version of the pack that has all the legacy
textures anyway, so we could do that route of having a beta, and going from
there. Just let me know so I don't screw up.

On Sun, Jan 18, 2015 at 11:56 AM, Oddface <notifications@github.com> wrote:

> As someone who played vanilla for years with the regular John Smith pack
> before moving onto modded Minecraft, JSTR just kinda looks wrong to me. And
> this change could very well have the same effect on someone who has been
> using JSTR for years. An interesting experiment could be to make JSTR the
> overwrite pack and look at the response. My guess is that the people who
> feel strongly enough about one style or another to download an overwrite
> pack is always going to be a minor fraction of the user base. If I'm wrong
> about that, changing it back wouldn't be a big deal. I think now would be a
> good time to experiment with big changes like this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/pull/49#issuecomment-70415700>
> .
>



-- 
Patrick Geneva | Administrator | pgb@soartex.net

**Comment by Oddface** [comment]
If we could make it two separate packs to start with, that would probably be the best option.

**Comment by lesdmark** [comment]
I really don't care for the look of the legacy ores either. I agree that 2 packs is a better idea. I wouldn't be using the pack if it was the legacy look it just doesn't suit my building style or the way I picture my world looking.

**Comment by Oddface** [comment]
Alright, guess it's settled then. Two packs. Whenever you're ready, @goldbattle.

**Comment by goldbattle** [comment]
We can do a single main pack, and an optional overlay pack, would that
work. From my past experience with soartex, maintaining multiple ore
versions etc, splits the team apart. Not sure if that is something that has
been considered yet. Thoughts?

On Sun, Jan 18, 2015 at 8:32 PM, Oddface <notifications@github.com> wrote:

> Alright, guess it's settled then. Two packs. Whenever you're ready,
> @goldbattle <https://github.com/goldbattle>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/pull/49#issuecomment-70436745>
> .
>



-- 
Patrick Geneva | Administrator | pgb@soartex.net

**Comment by lesdmark** [comment]
The legacy being the overlay is fine with me and that would be the easiest way to do it. I keep forgetting you can do that with the 1.7.x packs

**Comment by Oddface** [comment]
Splitting the team shouldn't become a major issue. Converting an ore from one style to another isn't a big deal in most cases.  It's not that much extra work to maintain. As for the main pack and overwrite pack, it does mean that one style would be marginalized. Can an overwrite pack be in the FTB launcher?

**Comment by goldbattle** [comment]
I might be able to get that worked out, I'll ask.

As for these ores, I am feeling it would be easiest to maintain them as a
mod patch.

On Mon, Jan 19, 2015 at 4:43 AM, Oddface <notifications@github.com> wrote:

> Splitting the team shouldn't become a major issue. Converting an ore from
> one style to another isn't a big deal in most cases. It's not that much
> extra work to maintain. As for the main pack and overwrite pack, it does
> mean that one style would be marginalized. Can an overwrite pack be in the
> FTB launcher?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/pull/49#issuecomment-70467515>
> .
>



-- 
Patrick Geneva | Administrator | pgb@soartex.net

**Comment by Oddface** [comment]
So should we make a new repo for that?

**Comment by goldbattle** [comment]
That's what I was asking, I see it as easier to just have a single mod
folder here that has all the overrides in it. Allows me to simple compile
the normal pack with it skipping over that folder, and also allows anybody
to make the override pack.


On Mon, Jan 19, 2015 at 8:38 AM, Oddface <notifications@github.com> wrote:

> So should we make a new repo for that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/pull/49#issuecomment-70493075>
> .
>



-- 
Patrick Geneva | Administrator | pgb@soartex.net

**Comment by Oddface** [comment]
Alright, so I just create a folder called Legacy_Overwrites, put all the Legacy textures there, with the correct folder structures of course, and you do the rest?

**Comment by goldbattle** [comment]
Yep

**Comment by Oddface** [comment]
Is it just me or is ctm completely busted in our 1.7 packs? I'm done with the overwrites folder except the ctm stuff.

**Pull request closed without merging**
