### PR TITLE
Ancient Trees v1.2.2

### PR DESCRIPTION
**Pull request by ScottKillen**

### CODE REVIEW

**Comment by lesdmark** [comment]
Changing the log sides for sure I have seen some of those doors in JS before as alternates not sure I think some of them do look a bit dokucraft though. I could see what i can dig up later to see for sure which ones might need to go.

**Comment by ScottKillen** [comment]
@lesdmark Not everything on that texture sheet is going into this commit...

**Comment by lesdmark** [comment]
My bad i am going to have to wait till i am home to be able to look at all of the ones you have in the pull request. The PC I'm on at the moment doesn't seem to want to show me half of them.

**Comment by ScottKillen** [comment]
see comments by @Oddface on the commit itself. I have more work to do. :grinning:

**Comment by ScottKillen** [comment]
OK, I believe all of the questionable textures are replaced. Ready for you, @Oddface

**Comment by Oddface** [comment]
Oh, I missed one, the kiparis leaves. Other than that looks all good :+1:

**Comment by ScottKillen** [comment]
OK @Oddface I replaced those kiparis leaves/ :wink:

**Pull request merged**
