### PR TITLE
Just unloading my repository..

### PR DESCRIPTION
**Pull request by Bordissed**
I've tried to keep the quality to a certain standard, some textures may still be kind of crappy though, they're mostly 32x versions of the already existing textures, there are some exceptions. (didn't overwrite anything already existing, alts do have a purpose)  

Also, i didn't put in any texture (hopefully) that has parts from texture packs other than JohnSmith (atleast not without having them just as a base for further editting).

Okay... maybe some things from Dokucraft here and there...

Mods Affected:

-Ancient Warfare (Blocks, items, and most importantly, gate model textures)
-Automagy (Mod texture support for some stuff, not all though)
-Biomes 'O Plenty (some...items?,and blocks?, i sure hope i didn't screw up the whole aesthethic of the dirt types)
-Botania (Flowers, lots of flowers, item textures, some blocks?)
-Ender IO (New Beta 2.3 stuff)
-Extra Utilities (Missing trashcans?)
-Flaxbeard's Steam Craft (Alt Darker Textures, aaand some items?)
-Funky Locomotion (Frames and wrench)
-Immersive Engineering (ALOT, just not models, yet...)
-Primitive Mobs (Items and maybe a couple models?)
-Railcraft (Some Firestone related textures, provisory if needed be, also didn't do the actual block...)
-Redstone_Arsenal (Armor textures, yes, the easiest to do since they're the only ones that aren't animated)
-Simply Jetpacks (General Update, didn't put in the 3d model textures, they're basic to say the least...)
-Statues Mod (It's there now, even though the actual mod is impossible to download, call it defunct textures...)
-Thaumcraft 4 (Added some things, some alts which in my modest opinion everyone should take a look at, and generaly missing stuff, i do love this mod)
-Thaumic Horizons (Some textures, items, models, the usual. Some seem a bit bare to me but not bad enough to not include them... Take them as replacements until i do better ones?)
-Tinkers Construct (Couple textures, materials mainly, and some misc. items)
-Witchery (i'll need to revisit many of these but for now they'll do, i hope...)

Not sure how much time i'll need until i finish more textures... i'll keep in touch.

PS: threw in some alt textures, check them out and decide which ones look best.

### CODE REVIEW

**Comment by damonmensch** [comment]
That's a lot to dump at once... maybe someone should double check for possible dokucraft textures, better safe than sorry in my opinion.

**Comment by damonmensch** [comment]
Also I thought we were avoiding that whole upped texture thing, where it's just a higher version of the mod's default texture.

**Comment by artdude543** [comment]
Yeah this would need massive checking before being pulled in. Might be better in parts instead of one massive dump. I assume that "upped" textures are generally not allowed. Should really be custom created for the resourcepack rather than re-scaling the default textures.

**Comment by goldbattle** [comment]
I would just wait to hear back from glow, I would assume he is going through them right now.
Either way, thank you for the textures!

**Comment by Glowstrontium** [comment]
There is definitely some good stuff in here, much of which is based on the JS textures.  The main issue I see is there seems to be lots of 64x64 textures mixed in, and unless the textures in question are 64x in the mod's stock (which is very rare), there should not be any textures of this resolution.  As for the "upped" 32x32 textures, which seem to be mostly limited to the item sprites here, back in the day we used to use the Faithful 32x textures (in accordance to the license) as placeholders until something better was made, because they generally look less out of place in-game than the stock 16x16 ones.

The main problem here is, it's extremely difficult to go though everything because it's all lumped into one commit (I always generally commit each mod separately).

**Comment by Oddface** [comment]
Lots of good stuff here, just a bit of a messy commit. 64x textures can be committed here: https://github.com/John-Smith-Colossal-Modded/JS-Cl-1.7x
Scaled down versions for this repo would be appreciated. I'll start looking through the alts. Definitely some better-looking stuff in there. Thanks!

**Comment by Oddface** [comment]
As for Faithful style textures, I have no problem with them as long as they don't look worse than the default (which can happen if it's a bad upscale). These all look fine in my opinion.

**Comment by Oddface** [comment]
Dokucraft textures are only allowed if they're from or derived from the original pack and not from the continuation. Any textures taken from the new Dokucraft and its mod support (or recognizably derived from them) need to be removed before the next update. But then again, Dokucraft isn't supposed to use our textures, and I still see some over there... Gah, copyrights ruin everything.

**Comment by Oddface** [comment]
Oh, and you mention BoP textures, but I can't find any. Maybe they got lost in the shuffle?

**Comment by Bordissed** [comment]
OK, about this last update, sorry for the mess, i didn't realise the actual instructions on how to dump textures were in the end, believe it or not i just opened github, selected my best stuff, and through trial and error managed to get it to you guys, only THEN i thought to myself:
...gee Bord, this page page is awfully long i wonder what's at the end. 
So... 
Sorry. 
I was kind of an Idiot.

On a more usefull note...
About Biomes 'o plenty: I did indeed forget to add the textures, i only added the some items, Jars of stuff, which i believe are not very John smithy...  I had dirt textures which i based on some Dokucraft textures i edited beyond recognition, but i dunno if they fit with the already existing aesthethic... i mean, they're close but meh...

About the rest:
i'll have to revisit a lot of these mods, block textures are easy to do, since you pick up parts of certain textures, mash them up real good and in the end they just don't have anything recognisable...(they still look good though, i hope).

Items: i'm planning on reworking alot of the stuff i did. Thaumcraft was one of the first mods i did texture support for, an one i revisited often, it kindda started me on this rampant course of mine...
The rest came along as necessity called.

Faithfull stuff: some of these mods had almost their entire item and block textures made in just one afternoon, hence me saying i'll do some revisiting on them.
try and add a John Smithy touch.

Dokucraft: i'll find any of these little demons and personally see to their elimination, i'll send a coment (or any other regional equivalent of communication) with their locations ASAP. 

64x stuff: when i did these i had parts of the 64x version of the pack installed and since back then these textures were for me and my friends to use, so i really didn't think of making them 32x again, i'll see about rectifying it... (some items may be just very detailled versions of items... some i think i have 32x alts of, i'll see if i can find them...)

Future stuff:
--Model Textures for "Immersive Engineering" (yup, i'm digging myself a nice big hole to put myself into...)
--Some work on the Flaxbeard's Steampower Exosuit to make it presentable (believe it or not, the textures are done, just not polished..)
--Botania textures, (I kind of owe that to Vazkii, she's Portuguese and so am i, so i gotta support my peoples, also it's a pretty neat mod)


And that's all for now, ...phew. 
That was a lot of stuff to cover.
Cheers!

**Comment by Bordissed** [comment]
Here's the Kill List for Dokucraft.
---------------------------------------------------------------------------
(Changed, but not enough)
.
Ancient_Warfare\assets\ancientwarfare\textures\items\npc\combat_order.png
Ancient_Warfare\assets\ancientwarfare\textures\items\npc\routing_order.png
Ancient_Warfare\assets\ancientwarfare\textures\items\npc\work_order.png
.
Statues_Mod\assets\statues\textures\items\marteau.png
.
Thaumcraft_4\assets\thaumcraft\textures\items\clothboots.png
Thaumcraft_4\assets\thaumcraft\textures\items\cultistboots.png
Thaumcraft_4\assets\thaumcraft\textures\items\cultistplatechest.png
Thaumcraft_4\assets\thaumcraft\textures\items\cultistplatehelm.png
Thaumcraft_4\assets\thaumcraft\textures\items\cultistboots.png
Thaumcraft_4\assets\thaumcraft\textures\items\cultistplateleaderhelm.png
Thaumcraft_4\assets\thaumcraft\textures\items\cultistplatelegs.png
Thaumcraft_4\assets\thaumcraft\textures\models\watcher.png
.
Witchery\assets\witchery\textures\items\ingredient.boltAntiMagic.png
Witchery\assets\witchery\textures\items\ingredient.boltHoly.png
Witchery\assets\witchery\textures\items\ingredient.boltSilver.png
Witchery\assets\witchery\textures\items\ingredient.boltSplitting.png
Witchery\assets\witchery\textures\items\ingredient.boltStake.png

---------------------------------------------------------------------------
(Identical)
.
ImmersiveEngineering\assets\immersiveengineering\textures\items\blueprint.png
ImmersiveEngineering\assets\immersiveengineering\textures\items\tool_hammer.png

---------------------------------------------------------------------------
(Not sure if safe or not)
.
Thaumcraft_4\assets\thaumcraft\textures\items\clothchest.png
Thaumcraft_4\assets\thaumcraft\textures\items\clothchestover.png
Thaumcraft_4\assets\thaumcraft\textures\items\clothlegs.png
Thaumcraft_4\assets\thaumcraft\textures\items\clothlegsover.png
Thaumcraft_4\assets\thaumcraft\textures\items\cultistplateleaderchest.png
Thaumcraft_4\assets\thaumcraft\textures\models\robes_1.png
Thaumcraft_4\assets\thaumcraft\textures\models\robes_1_overlay.png
Thaumcraft_4\assets\thaumcraft\textures\models\robes_2.png
Thaumcraft_4\assets\thaumcraft\textures\models\robes_2_overlay.png
.

**Comment by Oddface** [comment]
Alright, I've removed the stuff from the first two lists, except the bolts, which are derived from the original pack. The stuff in the last list looks to be fine.

**Comment by lesdmark** [comment]
I had kind of started working on Botania as no one had done anything with it for a while. The upscales are nice placeholders though. I have been trying to keep both true to the original textures as well as adding a JS twist to them in addion to taking into consideration the original plants they are based off of. It takes me a while to come up with something I like as a result.

**Comment by Bordissed** [comment]
For now i'm thinking of working on Immersive Engineering so i think i wont do anything major with botania, and if anything i'll just do some blocks.
As for Immersive... more model textures coming Soon™.

**Comment by lesdmark** [comment]
Sweet we need some IE goodness (not the browser mind you). Just try to make sure the textures are 32x. or an easier way to look at it is double the resolution as some of the mods use weird sized textures. of course if a mod is already using 32x then we want to replace them with JS type 32x textures not upscale them further.

**Comment by Greenhawk837** [comment]
If you do end up making any 64x textures feel do free to make a push request to the 64x modded repo
https://github.com/John-Smith-Colossal-Modded/JS-Cl-1.7x

**Pull request merged**
