### PR TITLE
ExtraUtilities: Update and fix misaligned low contrast gravel road textures

### PR DESCRIPTION
**Pull request by ScottKillen**
Before (note misaligned corners at center):

After:

### CODE REVIEW

**Comment by Oddface** [comment]
I don't wanna sound negative here, because this is a very well done texture. It's more of a style thing. The bright highlights on the edges generally isn't used in John Smith. Look at this slab top texture for example:
stone_slab_top
The top and right sides are brighter than the bottom and left sides, but still darker than the lines before them, if that makes sense. It's just something to keep in mind, not that this whole technique is banned or anything, it should just should be used sparingly. We should probably make a style guide for this type of stuff.

**Comment by ScottKillen** [comment]
Constructive criticism is not negative. I will adjust the textures to mute the highlights on the embossing.

**Comment by ScottKillen** [comment]
and...thanks, @Oddface . :grinning:

**Comment by Oddface** [comment]
Thanks for being a good sport :+1: 
Also, I know using the normal gravel texture might be more consistent, but something less brown like the original texture might make more sense for a fancy gravel road with bricks on the sides.

**Comment by ScottKillen** [comment]
@Oddface it is all about doing the best job we possibly can. That doesn't happen without embracing constructive ideas.

I agree regarding the gravel. I actually had an internal debate with myself. The texture in the mod uses a parquet pattern...though I know RWTema got the idea for the gravel roads after seeing the textures I did for Soartex. So I dunno...use a parquet, or use a muted "road-like" gravel. Here is the original texture from the mod in action:

300px-gravel_road_connected_textures

Any input from anyone on this would be appreciated.

I also am going to make the brick borders look similar to the slab top texture (that you also posted above).

**Comment by Oddface** [comment]
Well, it's made from gravel bricks, so I guess a parquet pattern would make more sense.

**Comment by ScottKillen** [comment]
Roger that.

**Comment by ScottKillen** [comment]
OK. I think these are much better:

**Comment by Oddface** [comment]
I really like the new gravel brick. The parquet pattern looks a little blurry, though. You could  replace it with the normal gravel brick texture if you want. The brick and gravel brick bleed a little into each other in some spots. You can make the brick edges a little more solid and maybe add a little shading to fix that.

**Comment by ScottKillen** [comment]
I will work on the shading of the border brick.

When I get a chance tonight, I'll post an example of the textures with the gravel brick and one with the gravel brick in an unrotated parquet pattern and get some feedback.

**Comment by lesdmark** [comment]
It does look a bit blurry. Perhaps bringing the two tones closer to each other as well. I do like the herringbone pattern though.

**Comment by ScottKillen** [comment]
Yeah, the blurriness is strictly from the 45 degree rotation. The unrotated textures are sharp. I will post examples in a bit.

**Comment by ScottKillen** [comment]
OK...here is the best result so far:

**Comment by Oddface** [comment]
Looks good! The brown-ish color on the bricks is more of a Legacy thing, so maybe try making them more gray like the JSTR stuff.

**Comment by ScottKillen** [comment]
Do you want me to also recolor the stone slab? The reason I matched with it
is in case someone builds sidewalks with the slabs. If the bricks don't
match then the brown of the slab is overwhelming.

**Comment by Oddface** [comment]
You're using the 64x pack as an overlay, which is based on Legacy textures. In JSTR the slabs are gray.

**Comment by Greenhawk837** [comment]
Yeah, there's two 64x packs, one based on Legacy and the other on JSTR

**Comment by ScottKillen** [comment]
What a newb thing to do? :grinning:

OK...I'm headed to work, but I wanted to post the two versions to get input: (I have doubly zoomed the image for better viewing here.)

Current:
brown-sample

Matching JSTR slab:
grey-sample

Will I need to tint the gravel brick texture? (maybe add some brown? :stuck_out_tongue_closed_eyes:)

**Comment by Oddface** [comment]
A little bit of brown on the gravel should do the trick.

**Comment by goldbattle** [comment]
I assume that all these other variations you have posted can be used in another area of chisel, I really like the gravel one, and the tan colored bored. I hope that those could get used in another area of the mod. Besides that, these look good.

**Comment by ScottKillen** [comment]
Thanks, @goldbattle !

I don't know of another suitable place, but I could certainly put them in as alternates (I will probably use one of them myself.)

What is the standard way of supplying alternates in this pack?

I plan on providing the very first set, the two sets just above this. For the final "official" set, I will give the gravel areas a brown tint, similar to the brown brick just above (which were accidentally colored to match legacy slabs. :wink: )

**Comment by lesdmark** [comment]
that last one that matches the JSTR slab looks good. and like Oddface said, bit of the gravel color and should be perfect.

**Comment by ScottKillen** [comment]
Oh...and I'll also recolor the gravel brick block to match...

**Comment by goldbattle** [comment]
Currently no way to ship alts, usually I just make a /alts/ folder near the
original texture.

On Mon, Feb 2, 2015 at 4:52 PM, lesdmark <notifications@github.com> wrote:

> that last one that matches the JSTR slab looks good. and like Oddface
> said, bit of the gravel color and should be perfect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/pull/68#issuecomment-72545872>
> .
>



-- 
Patrick Geneva | Administrator | pgb@soartex.net

**Comment by ScottKillen** [comment]
OK. Here is the final result. I also added some alternates.
untitled-1

**Pull request merged**
