### PR TITLE
BoP Plank Tweaks

### PR DESCRIPTION
**Pull request by damonmensch**
Change BoP planks to new standards.

### CODE REVIEW

**Comment by Greenhawk837** [comment]
These look great! but try making the ethereal planks a little more saturated or perhaps even a green version of the magic planks might suit them really well.

**Comment by damonmensch** [comment]
Tweaked the vibrance and saturation settings a bit.
plank_ethereal

**Comment by Greenhawk837** [comment]
This is just me being picky, but I find that it could to be a touch less green.
ethereal

**Comment by damonmensch** [comment]
I'm a tad confused, first you suggested more saturation, now less? Also bringing this down in level to be closer to Magic Planks would make them too similar to Willow, in my opinion.

**Comment by Greenhawk837** [comment]
Sorry, I did mean less in the first place, don't know how I managed to do that.

But anyway in the version I posted before it's still easily recognizable from the willow planks. and they fit into the JSTR style
ethereal
plank_willow

**Comment by damonmensch** [comment]
How is this? It's more muted, more closely resembling Magic Planks but with more green in it.
plank_ethereal

**Comment by Oddface** [comment]
I like the version Sam posted the best, mainly for the sake of variety.

**Comment by damonmensch** [comment]
Removed mine so Greenhawk can push his. I didn't notice his was different from mine. The two looked so similar to me on my monitor I thought he just reposted mine.

**Pull request merged**
