### PR TITLE
BluePower Updates

### PR DESCRIPTION
**Pull request by damonmensch**

### CODE REVIEW

**Comment by Oddface** [comment]
We recently made a change to how we do ingots and gems. You might be using an older version of the pack as a reference point. Just download the newest version and try to match that instead. Other than those minor problems, great work!

**Comment by ScottKillen** [comment]
The purple amethyst color is truer to the original mod textures (which are a deep purple). Why the change to pink? Also, to me, the pink is very bright and does not seem to fit well in-game.

At the very least perhaps don't delete the purple, but offer them as alternates (see how this is done for with other mods in this repo)

**Comment by Oddface** [comment]
He was matching it to the BoP amethyst, which is pink. It's an issue about resource pack consistency vs consistency with the default textures. It's not always easy to know where to draw the line. If there isn't an ore dictionary entry for the two amethyst types, that essentially makes them the same thing, I would vote purple. We should not do alternates in this case because there are tools and stuff that would also have to have alts to keep consistency.

**Comment by ScottKillen** [comment]
I forgot about tools...and I sorta created this controversy only providing block textures and not items.

I prefer the purple, but I hate to ask@damonmensch redo so many textures. Unless @Oddface pushes for the purple, I withdraw my remarks and will handle my personal preference through overrides.

Also, @damonmensch , I forgot to mention that these textures are very well done. :+1: to you/

**Comment by Oddface** [comment]
Don't worry about it. The pink amethyst stuff can stay for now and if you end up making purple versions you can commit that later.

**Comment by damonmensch** [comment]
Yeah sorry this was done porting the older, I'll alter the ingots to match the new style later today/topnight and send a new comit. I wasn't aware the gems were changed. Again the amethyst was taken from BoP, the other gems were done from the old RedPower2 versions. I'll check the gems as well.

**Comment by Oddface** [comment]
:+1:

**Comment by damonmensch** [comment]
Updated the ingots and gems to match the new standards. Got to say the hue swap on them came out nicely.

Also may I suggest adding the new gem templates to the templates repository? Also maybe we should add some of the mod ores as well, if anyone happens to have the overlays.

**Comment by Oddface** [comment]
Nice work!

**Pull request merged**
